### PR TITLE
Fix: onboarding routing, profanity filter

### LINKED ISSUE #141: bug: Fix Onboarding Flow for New Users
### Summary

Problem:
After signing up and logging back in, if the user redirect back to the login and sign in - users are being redirected directly to the matching page instead of completing the onboarding flow. This also affects profile completion, leading to incomplete user data.

Solution: 
Update the authentication and routing logic to ensure that users who have not completed onboarding are redirected to the onboarding page upon login.

### Steps to reproduce

1. Sign up as a new user
2. Complete partial onboarding 
3. Log out of the application
4. Log back in with the same credentials
5. Observe the redirect behavior after login

### Logs / console output

```shell

```

### Area

_No response_

### PR DESCRIPTION
**Pull request by Nsujatno**
## What changed
- Fixed onboarding routing so if u log out and log back in on any step it remembers where u need to be
- added basic profanity filter on bio, first name, and last name sections in create profile

## Why
- 

## How to test
1. go through the onboarding

## Screenshots (UI changes)
- N/A

## Checklist
- [x] PR title is conventional (feat:, fix:, chore:, docs:)
- [x] Tested locally
- [x] No secrets/credentials logged or committed
- [x] This PR is reasonably sized (if large, explained why)

## Notes for reviewers
- tested full end to end workflow and logging back in at each step to see if it works, it does
- profanity filter is still easily bypassable but its a cheap solution for now and prevents at least accidental profanity, if someone says something really bad they'll just get reported anyway

### CODE REVIEW

File: src/contexts/authContext/index.tsx [hunk 1]
```diff
@@ -42,10 +43,21 @@ export function AuthProvider({ children }: { children: React.ReactNode }) {
     setLoading(false);
   }
 
+  // login page can call after sign in so user context is fresh
+  const reloadUser = useCallback(async () => {
+    if (auth.currentUser) {
+      await auth.currentUser.reload();
+      const refreshedUser = auth.currentUser;
+      setCurrentUser(refreshedUser ? { ...refreshedUser } : null);
```
Comment (ryanpolasky) [inline src/contexts/authContext/index.tsx]: Spreading a Firebase User into a plain object is lil risky here. Firebase’s docs recommend doin current user access w/ `auth.currentUser`/the auth observer, so we should store the real refreshed user object instead of cloning it and potentially losing any User semantics.

File: src/contexts/onboardingContext.tsx [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+                try {
+                    const [profileRes, surveyRes] = await Promise.all([
+                        getProfile(currentUser.uid),
+                        getSurvey()
+                    ]);
+
+                    if (!active) return;
+
+                    // If either critical call failed at the API level (e.g. 500), consider it an error
+                    if (!profileRes.ok && profileRes.code !== "404") {
```
Comment (ryanpolasky) [inline src/contexts/onboardingContext.tsx:62]: This early return sets `isError` but leaves any previously computed `hasProfile`/`hasPicture`/`hasSurvey` values untouched. If a refresh fails after a prior success, routing can run off stale onboarding state, so we should prolly reset the derived flags before returning on API error.

File: src/contexts/onboardingContext.tsx [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+                            profileRes.data.profile_picture_url.length >= MIN_PHOTOS
+                        );
+                    } else {
+                        setHasProfile(false);
+                        setHasPicture(false);
+                    }
+
+                    if (surveyRes.ok && surveyRes.data) {
+                        setHasSurvey(true);
+                    } else if (!surveyRes.ok && surveyRes.code !== "404") {
```
Comment (ryanpolasky) [inline src/contexts/onboardingContext.tsx:81]: Same issue as that other one, we mark the context as errored but keep whatever old survey state was already in memory. That can make the app think onboarding is complete when the latest status check actually failed.

File: src/hooks/useOnboardingRouting.ts [hunk 4]
```diff
@@ -0,0 +1,42 @@
+import { useAuth } from "@/contexts/authContext";
+import { useOnboarding } from "@/contexts/onboardingContext";
+
+export function useOnboardingRouting() {
+    const { currentUser, userLoggedIn } = useAuth();
+    const { isLoading: onboardingLoading, hasProfile, hasPicture, hasSurvey } = useOnboarding();
```
Comment (ryanpolasky) [inline src/hooks/useOnboardingRouting.ts]: We’re ignoring `isError` from the onboarding context, so backend failures get collapsed into normal routing decisions. Might be best to add an explicit error branch instead of redirecting users to `createProfile/upload/survey` when the real problem is that onboarding status couldn't be loaded.

File: src/app/onboarding/createProfile/page.tsx [hunk 5]
```diff
@@ -1,16 +1,25 @@
 "use client";
 import React from "react";
 import Image from "next/image";
+import { isProfane } from "@/utils/profanity";
```
Comment (ryanpolasky) [inline src/app/onboarding/createProfile/page.tsx:4]: We should *prolly* add some backend checks too at some point. Could u open a Kanban issue for the backend repo & assign it to Atharva? Add some details about ur implementation on frontend/what's done/what isn't.

File: src/app/onboarding/housing/page.tsx [hunk 6]
```diff
@@ -73,6 +74,7 @@ const sendOnboardingData = async () => {
 
 function OnCampusUI() {
 	const router = useRouter();
+	const { markSurveyCompleted } = useOnboarding();
 	const handleNextStep = async () => {
```
Comment (ryanpolasky) [inline src/app/onboarding/housing/page.tsx:78]: Might wanna re-validate profanity inside the submit handler before calling `createProfile()`. Right now the button disabled state is doing the enforcement, but the submit path itself does not guard against profane values.

File: src/app/dashboard/layout.tsx [hunk 7]
```diff
@@ -14,23 +15,26 @@ export default function AppLayout({
...
 }) {
   const { userLoggedIn, loading } = useAuth();
+  const { requiredRoute, isLoading, isReady } = useOnboardingRouting();
   const router = useRouter();
 
   useEffect(() => {
     if (!loading && !userLoggedIn) {
       router.push("/authentication?toast=not-signed-in");
+    } else if (!loading && userLoggedIn && isReady && requiredRoute) {
+      router.push(requiredRoute);
```
Comment (ryanpolasky) [inline src/app/dashboard/layout.tsx]: This redirect should probably use `router.replace` instead of push, cuz this is a guard redirect, keeping the blocked route in browser history can create a back-button bounce loop.

File: src/app/dashboard/layout.tsx [hunk 8]
```diff
@@ -14,23 +15,26 @@ export default function AppLayout({
   children: React.ReactNode;
 }) {
   const { userLoggedIn, loading } = useAuth();
+  const { requiredRoute, isLoading, isReady } = useOnboardingRouting();
   const router = useRouter();
 
   useEffect(() => {
     if (!loading && !userLoggedIn) {
       router.push("/authentication?toast=not-signed-in");
```
Comment (ryanpolasky) [inline src/app/dashboard/layout.tsx]: > This redirect should probably use `router.replace` instead of push, cuz this is a guard redirect, keeping the blocked route in browser history can create a back-button bounce loop.

same

File: src/app/onboarding/uploadPictures/page.tsx [hunk 9]
```diff
@@ -179,6 +195,7 @@ export default function UploadPicturesPage() {
 		setIsLoading(true);
 
 		setIsLoading(false);
+		markPictureUploaded();
```
Comment (ryanpolasky) [inline src/app/onboarding/uploadPictures/page.tsx:198]: This marks onboarding state as complete unconditionally right before navigation. We should def make sure it only runs after the photo upload/save has definitely succeeded server-side, otherwise the client context can get ahead of backend truth.

**Review by ryanpolasky — CHANGES_REQUESTED** [review]
Some things to consider here before merge. Thanks a ton for your work! :)

File: src/app/onboarding/uploadPictures/page.tsx (hunk 9 above)
Comment (Nsujatno) [reply src/app/onboarding/uploadPictures/page.tsx:198]: the photos get uploaded immediately after selecting and cropping so when they click the button backend already confirmed the upload

**Review by ryanpolasky — APPROVED** [review]
good to go, take a look at the think i pinged u at in discord, but i'll merge this now
